Allow provider specific customization of token body
jupyterhub/oauthenticator pull request #599
Opened 2023-04-19 14:56 UTC by jabbera

Also change Azure AD to url encoded.

Fixes: https://github.com/jupyterhub/oauthenticator/issues/598

2023-04-19 15:15 UTC, GeorgianaElena requested changes
Thank you very much for reporting and fixing this @jabbera.

The issue in https://github.com/jupyterhub/oauthenticator/issues/598 seems to be the same with https://github.com/jupyterhub/oauthenticator/issues/564. And since this is impacting all the oauthenticators I believe it's worth modifying the base OAuth class directly instead of allowing it it to be customized by different oautnenticatot classe.

2023-04-19 15:37 UTC, jabbera commented
@GeorgianaElena  all set

2023-04-21 18:22 UTC, jabbera commented
Does this need anything else?

2023-04-21 20:45 UTC, consideRatio reviewed
# Investigation

<details>
<summary>Click to see investigation</summary>

I looked in the previous release of oauthenticator, version 15.1.0, and concluded that Content-Type was set to x-www-form-urlencoded for: azuread, bitbucket, google.

But:
- azuread, bitbucket, google set Content-Type: application/x-www-form-urlencoded with details about utf-8 etc.
- auth0 set Content-Type: application/json
- cilogon, generic, github, gitlab, globus, okpy, openshift provided no Content-Type header
- mediawiki relied on mwoauth library

Since Content-Type influence what is passed, the fix ought to be ensure we declare Content-Type correctly for all requests based on what data we pass.

- auth0, seems like `"Content-Type": "application/json"` is correct
  ```python
  body=json.dumps(params),
  ```
- azread, seems like `'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'` is correct
  ```python
  data = urllib.parse.urlencode(params, doseq=True, encoding='utf-8', safe='=')
  ```
- bitbucket, seems like `"Content-Type": "application/x-www-form-urlencoded;charset=utf-8"` is correct
  ```python
  body=urllib.parse.urlencode(params).encode('utf-8'),
  ```
- google, seems like `"Content-Type": "application/x-www-form-urlencoded"` is correct
  ```python
  body = urllib.parse.urlencode(
              dict(
                  code=code,
                  redirect_uri=self.get_callback_url(handler),
                  client_id=self.client_id,
                  client_secret=self.client_secret,
                  grant_type="authorization_code",
              )
          )
  ```
- generic, not providing a Content-Type, actually urlencodes params, not setting Content-Type header is likeley incorrect
  ```python
  body=urlencode(params),
  ```
- cilogon, github, gitlab, openshift provides an empty string as POST body - not setting Content-Type header is likely correct
- globus, okpy, makes use of a GET request where there is no POST body - not setting Content-Type header is correct

</details>

# Conclusion

Overall, I think we can't provide a standardized Content-Type across our authenticators, but need to let the authenticators decide on it setting that header or not, and to what.

- For GET requests (globus, okpy) and POST requests with a empty-string body (cilogon, github, gitlab, openshift), we should not set Content-Type at all I think.
- For POST requests where we urlencode params (azuread, google, bitbucket, generic), we should set `application/x-www-form-urlencoded` I think.
- For POST requests where we pass json encoded params (auth0), we should set `application/json` I think.

> **EDIT: New conclusion**
> I got this wrong, I do think we can provide a standarized Content-Type across our authenticators, and that should be what all authenticators support thanks to the OAuth2 specification, x-www-form-urlencoded with an utf-8 charset. But we need to be explicit about the content-type, otherwise some assume json etc.

# Related reading

- [About Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type)
- [About Content-Type with no body for POST requests](https://stackoverflow.com/a/29784642/2220152)

2023-04-21 21:34 UTC, jabbera commented
Thanks. This is the opposite of the other feedback I received which asked me to centralize it instead of doing it at the provider level. I'm happy to revert it and add the other changes you mentioned in the other providers. Are we fairly certain this is the desired end state?

2023-04-22 09:27 UTC, consideRatio commented on oauthenticator/tests/mocks.py
> -                code = body['code']
This section was removed and only influenced tests of auth0 that had been sent JSON in the Post body before, but now sends an urlencoded body like other does.

2023-04-22 09:28 UTC, consideRatio commented on oauthenticator/tests/mocks.py
> +        code = query['code'][0]
This is unchanged code beside intentation change when it was no longer nested in an `else` clause.

2023-04-22 09:28 UTC, consideRatio commented on oauthenticator/tests/test_globus.py
> -        token_request_style='post',
This was the default value anyhow.

2023-04-22 09:28 UTC, consideRatio commented on oauthenticator/tests/test_auth0.py
> -        token_request_style='json',
This was no longer accurate.

2023-04-22 09:35 UTC, consideRatio approved these changes
I had to think a lot before feeling confident about this change, the comment https://github.com/jupyterhub/oauthenticator/pull/599#pullrequestreview-1396378578 was a starting point for me to understand this well enough.

I pushed a few commits to finish up some details, but this looks good to me now!

Changes I made:
- Removed irrelevant Content-Type header on GET requests
- Switched to rely on Python's standard library to do the urlencoding
- Updated docstrings with details on Content-Type
- Cleaned up unused test configuration

2023-04-22 09:47 UTC, consideRatio commented
Thank you @jabbera for helping us get this fixed! I was wrong to suggest we needed to adjust the Content-Type for individual authenticators I think.

I added an EDIT note in my comment above:

![image](https://user-images.githubusercontent.com/3837114/233776634-9ee78b1e-68da-48a4-a70c-7578900b933a.png)

2023-04-22 12:00 UTC, jabbera commented
Glad we could get this there. The new extension points in the refactor are awesome.

2023-04-25 09:42 UTC, GeorgianaElena approved these changes
Awesome work! Thanks @jabbera, thanks @consideRatio 🎉 🚀

2023-04-25 09:42 UTC, merged

2023-04-25 11:02 UTC, jabbera commented
It works!